from openjdk:17-alpine as builder
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} Limits-Service-0.0.1-SNAPSHOT.jar
RUN java -Djarmode=layertools -jar Limits-Service-0.0.1-SNAPSHOT.jar extract

from openjdk:17-alpine
COPY --from=builder dependencies/ ./
RUN true
COPY --from=builder snapshot-dependencies/ ./
RUN true
COPY --from=builder spring-boot-loader/ ./
RUN true
COPY --from=builder application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]