version: '3.7'

services:
    currency-eureka-server:
        image: sumeetvvarma/ms2-currency-eureka-server:latest
        ports:
            - "8761:8761"
        networks:
            - currency-network
    currency-api-gateway:
        image: sumeetvvarma/ms2-currency-api-gateway:latest
        ports:
            - "8765:8765"
        networks:
            - currency-network
        depends_on:
            - currency-eureka-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://currency-eureka-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
    currency-exchange-service:
        image: sumeetvvarma/ms2-currency-exchange-service:latest
        ports:
            - "8000:8000"
        networks:
            - currency-network
        depends_on:
            - currency-eureka-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://currency-eureka-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
    currency-conversion-service:
        image: sumeetvvarma/ms2-currency-conversion-service:latest
        ports:
            - "8100:8100"
        networks:
            - currency-network
        depends_on:
            - currency-eureka-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://currency-eureka-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
    zipkin-server:
        image: openzipkin/zipkin:2.23
        ports: 
           - "9411:9411"
        networks:
           - currency-network
networks:
    currency-network: