version: '3.7'

services:
    currency-eureka-server:
        image: sumeetvvarma/ms2-currency-eureka-server:latest
        ports:
            - "8761:8761"
        networks:
            - currency-network

    currency-api-gateway:
        image: sumeetvvarma/ms2-currency-api-gateway:latest
        ports:
            - "8765:8765"
        networks:
            - currency-network
        depends_on:
            - currency-eureka-server
            - rabbitmq
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://currency-eureka-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_ZIPKIN_SENDER_TYPE: rabbit

    currency-exchange-service:
        image: sumeetvvarma/ms2-currency-exchange-service:latest
        ports:
            - "8000:8000"
        networks:
            - currency-network
        depends_on:
            - currency-eureka-server
            - rabbitmq
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://currency-eureka-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_ZIPKIN_SENDER_TYPE: rabbit

    currency-conversion-service:
        image: sumeetvvarma/ms2-currency-conversion-service:latest
        ports:
            - "8100:8100"
        networks:
            - currency-network
        depends_on:
            - currency-eureka-server
            - rabbitmq
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://currency-eureka-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            RABBIT_URI: amqp://guest:guest@rabbitmq:5672
            SPRING_RABBITMQ_HOST: rabbitmq
            SPRING_ZIPKIN_SENDER_TYPE: rabbit

    zipkin-server:
        image: openzipkin/zipkin:2.23
        ports: 
           - "9411:9411"
        networks:
           - currency-network
        environment:
           RABBIT_URI: amqp://guest:guest@rabbitmq:5672
        depends_on:
           - rabbitmq
        restart: always

    rabbitmq:
        image: rabbitmq:3.8.12-management
        ports: 
           - "5672:5672"
           - "15672:15672"
        networks:
           - currency-network

networks:
    currency-network: